// Frank #0906 round-14 (Batch C): country → approximate centroid
// lat/lng used by the Stats page mini-world-map to place the cyan
// "where I've been" dots. Hand-curated for the most common
// countries Frank has visited; if a country isn't in the dict the
// country still appears in the cards list below — only the dot is
// skipped (so an unlisted country doesn't dump to (0,0)).
//
// Coords are country centroids rounded to 1°. Good enough for a
// 600px-wide mini map where each pixel is ~6 degrees anyway.

export type CountryCentroid = { lat: number; lng: number; iso2: string };

export const COUNTRY_CENTROIDS: Record<string, CountryCentroid> = {
  中国: { iso2: 'CN', lat: 35, lng: 105 },
  Japan: { iso2: 'JP', lat: 36, lng: 138 },
  美国: { iso2: 'US', lat: 39, lng: -98 },
  韩国: { iso2: 'KR', lat: 36, lng: 128 },
  'South Korea': { iso2: 'KR', lat: 36, lng: 128 },
  香港: { iso2: 'HK', lat: 22, lng: 114 },
  'Hong Kong': { iso2: 'HK', lat: 22, lng: 114 },
  台湾: { iso2: 'TW', lat: 24, lng: 121 },
  Taiwan: { iso2: 'TW', lat: 24, lng: 121 },
  澳门: { iso2: 'MO', lat: 22, lng: 113 },
  Macau: { iso2: 'MO', lat: 22, lng: 113 },
  泰国: { iso2: 'TH', lat: 15, lng: 100 },
  Thailand: { iso2: 'TH', lat: 15, lng: 100 },
  越南: { iso2: 'VN', lat: 16, lng: 108 },
  Vietnam: { iso2: 'VN', lat: 16, lng: 108 },
  新加坡: { iso2: 'SG', lat: 1, lng: 103 },
  Singapore: { iso2: 'SG', lat: 1, lng: 103 },
  马来西亚: { iso2: 'MY', lat: 4, lng: 102 },
  Malaysia: { iso2: 'MY', lat: 4, lng: 102 },
  印尼: { iso2: 'ID', lat: -2, lng: 118 },
  Indonesia: { iso2: 'ID', lat: -2, lng: 118 },
  菲律宾: { iso2: 'PH', lat: 13, lng: 122 },
  印度: { iso2: 'IN', lat: 22, lng: 79 },
  India: { iso2: 'IN', lat: 22, lng: 79 },
  阿联酋: { iso2: 'AE', lat: 24, lng: 54 },
  英国: { iso2: 'GB', lat: 54, lng: -2 },
  'United Kingdom': { iso2: 'GB', lat: 54, lng: -2 },
  法国: { iso2: 'FR', lat: 46, lng: 2 },
  France: { iso2: 'FR', lat: 46, lng: 2 },
  德国: { iso2: 'DE', lat: 51, lng: 10 },
  Germany: { iso2: 'DE', lat: 51, lng: 10 },
  意大利: { iso2: 'IT', lat: 42, lng: 13 },
  Italy: { iso2: 'IT', lat: 42, lng: 13 },
  西班牙: { iso2: 'ES', lat: 40, lng: -4 },
  Spain: { iso2: 'ES', lat: 40, lng: -4 },
  澳大利亚: { iso2: 'AU', lat: -25, lng: 133 },
  Australia: { iso2: 'AU', lat: -25, lng: 133 },
  新西兰: { iso2: 'NZ', lat: -41, lng: 174 },
  'New Zealand': { iso2: 'NZ', lat: -41, lng: 174 },
  加拿大: { iso2: 'CA', lat: 56, lng: -106 },
  Canada: { iso2: 'CA', lat: 56, lng: -106 },
  墨西哥: { iso2: 'MX', lat: 23, lng: -102 },
  Mexico: { iso2: 'MX', lat: 23, lng: -102 },
  俄罗斯: { iso2: 'RU', lat: 60, lng: 95 },
  Russia: { iso2: 'RU', lat: 60, lng: 95 },
  土耳其: { iso2: 'TR', lat: 39, lng: 35 },
  Turkey: { iso2: 'TR', lat: 39, lng: 35 },
  埃及: { iso2: 'EG', lat: 26, lng: 30 },
  南非: { iso2: 'ZA', lat: -29, lng: 24 },
  巴西: { iso2: 'BR', lat: -10, lng: -53 },
  Brazil: { iso2: 'BR', lat: -10, lng: -53 },
  阿根廷: { iso2: 'AR', lat: -34, lng: -64 },
  Argentina: { iso2: 'AR', lat: -34, lng: -64 },
  瑞士: { iso2: 'CH', lat: 47, lng: 8 },
  Switzerland: { iso2: 'CH', lat: 47, lng: 8 },
  荷兰: { iso2: 'NL', lat: 52, lng: 5 },
  Netherlands: { iso2: 'NL', lat: 52, lng: 5 },
  葡萄牙: { iso2: 'PT', lat: 39, lng: -8 },
  希腊: { iso2: 'GR', lat: 39, lng: 22 },
  Norway: { iso2: 'NO', lat: 60, lng: 9 },
  Sweden: { iso2: 'SE', lat: 60, lng: 15 },
  Denmark: { iso2: 'DK', lat: 56, lng: 10 },
  Iceland: { iso2: 'IS', lat: 65, lng: -18 },
  Ireland: { iso2: 'IE', lat: 53, lng: -8 },
  Belgium: { iso2: 'BE', lat: 50, lng: 4 },
  Austria: { iso2: 'AT', lat: 47, lng: 14 },
  Czechia: { iso2: 'CZ', lat: 50, lng: 15 },
  Poland: { iso2: 'PL', lat: 52, lng: 19 },
  Hungary: { iso2: 'HU', lat: 47, lng: 19 },
  Greece: { iso2: 'GR', lat: 39, lng: 22 },
  Israel: { iso2: 'IL', lat: 31, lng: 35 },
  摩洛哥: { iso2: 'MA', lat: 31, lng: -7 },
  Kenya: { iso2: 'KE', lat: -1, lng: 37 },
  尼泊尔: { iso2: 'NP', lat: 28, lng: 84 },
  Nepal: { iso2: 'NP', lat: 28, lng: 84 },
  斯里兰卡: { iso2: 'LK', lat: 7, lng: 81 },
  'Sri Lanka': { iso2: 'LK', lat: 7, lng: 81 },
  缅甸: { iso2: 'MM', lat: 22, lng: 96 },
  柬埔寨: { iso2: 'KH', lat: 13, lng: 105 },
  Cambodia: { iso2: 'KH', lat: 13, lng: 105 },
  老挝: { iso2: 'LA', lat: 19, lng: 105 },
  Mongolia: { iso2: 'MN', lat: 46, lng: 105 },
};

export function getCountryCentroid(country: string): CountryCentroid | null {
  return COUNTRY_CENTROIDS[country] ?? null;
}